# Generated by Django 5.0.6 on 2024-05-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='note',
            name='timestamp',
            field=models.IntegerField(default=1716581634),
        ),
    ]
