# Generated by Django 5.0.6 on 2024-05-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_note_content_alter_note_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='timestamp',
            field=models.IntegerField(default=1716922192),
        ),
    ]
