# Generated by Django 5.0.6 on 2024-05-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_note_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='note',
            name='timestamp',
            field=models.IntegerField(default=1716925542),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
